import "./globals.css";
import { Baloo_Bhaijaan_2 } from "next/font/google";
import { getServerSession } from "next-auth";

const tajawal = Baloo_Bhaijaan_2({ subsets: ["latin"] });
export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	auth,
}: {
	children: React.ReactNode;
	auth: React.ReactNode;
}) {
	const session = await getServerSession();
	return (
		<html lang="ar" dir="rtl">
			<body className={tajawal.className}>{session ? children : auth}</body>
		</html>
	);
}
